### ISSUE TITLE
File is not found during code coverage report generation

### ISSUE THREAD

**Issue by emmanuelbenitez** [pester/AzureDevOpsExtension#22]
### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Version: 10.0.3

### Expected behaviour
When the task "PublishCodeCoverageResults" is used in a pipeline, the report contains the file and the user can see the line of file are covered or not

### Actual behaviour
In the log, the following warning are logged:
`2020-05-19T19:49:35:  File 'X.psm1' does not exist (any more).`

The report does not contains the file content:
![image](https://user-images.githubusercontent.com/22790093/82877767-e8bf6b80-9f3a-11ea-9213-07c81899029d.png)

### Steps to reproduce the problem
The PowerShell Module contains nested module.

**YAML Configuration**
```yaml
 - task: Pester@9
    displayName: "Test PowerShell Module with Pester"
    inputs:
      scriptFolder: '$(build.sourcesdirectory)'
      resultsFile: "$(build.sourcesdirectory)/PowerShellModuleProject.Tests.XML"
      CodeCoverageOutputFile: '$(build.sourcesdirectory)\coverage.powershell-module.xml'
      CodeCoverageFolder: '$(build.sourcesdirectory)'
      usePSCore: False
  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: "$(build.sourcesdirectory)/PowerShellModuleProject.Tests.XML"
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'PowerShell Module Tests'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(build.sourcesdirectory)\coverage.powershell-module.xml'
      pathToSources: '$(build.sourcesdirectory)'
      failIfCoverageEmpty: true
```
