### ISSUE TITLE
Please document how to use this better. Pester fails, because it can't find the module under test

### ISSUE THREAD

**Issue by plastikfan** [pester/AzureDevOpsExtension#47]
### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)
- Azure DevOps Server (on-premise TFS, if so what version)

Running on Azure DevOps Service (VSTS)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

Using latest version (task definition: Pester@10)

### Expected behaviour and actual behaviour
Run the tests succesfully, using latest version of Pester (5.0.3)

### Steps to reproduce the problem
Install the Pester Test Run from the marketplace in my Azure Organisation. I assume by doing so, any project within the organisation can define pipelines with a task: Pester@10.

To use the latest version of Pester set PesterVersion='LatestVersion|OtherVersion' and preferredPesterVersion to '5.0.3'.

I have 3 tasks under the same job:
1) bootstrap: installs and imports dependencies
2) build the module. The module is constructed by assembling all ps1 sources into the psm1 file.
3) run Pester. This needs to use the module built in the previous step, but how do  you correctly tell pester to use this just built module?

Here is my pipeline yaml:

```yaml
name: $(Build.DefinitionName)_$(Date:yyyyMMdd))

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  minor: 0
  patch: $(Build.BuildID)
  buildVersion: $(major).$(minor).$(patch)
  system.debug: true

stages:
- stage: Build
  jobs:
    - job: Build
      steps:
      - powershell: ./bootstrap.ps1
        displayName: 'Install pre-requisites'
      - task: PowerShell@2
        displayName: 'Perform build'
        inputs:
          pwsh: true
          failOnStderr: true
          targetType: 'filePath'
          filePath: '$(System.DefaultWorkingDirectory)/do-build.ps1'
      - task: Pester@10
        inputs:
          PesterVersion: 'LatestVersion|OtherVersion'
          preferredPesterVersion: '5.0.3'
          scriptFolder: '$(System.DefaultWorkingDirectory)\Elizium.FakeBuddy\Tests\*'
          resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
          usePSCore: true
          additionalModulePath: '$(System.DefaultWorkingDirectory)\Elizium.FakeBuddy\Output\Elizium.FakeBuddy\Elizium.FakeBuddy.psd1'
```

Please note that every thing works on local host, so this issue has nothing to do with me not writing correct powershell or writing faulty powershell tests. This is simply an issue of telling Pester on Azure to use the dynamically generated module.

I think the problem is something to do with "additionalModulePath", the documentation on this is not specific enough.

'$(System.DefaultWorkingDirectory) = the root of the git hub repo; FakeBuddy
The build task constructs the module at FakeBuddy/Elizium.FakeBuddy/Output/Elizium.FakeBuddy
and inside this location are Elizium.FakeBuddy.psd1 and Elizium.FakeBuddy.psm1

This is the module that Pester should be running the tests against.

Setting the additionalModulePath to "FakeBuddy\Elizium.FakeBuddy\Output\Elizium.FakeBuddy" (ie $(System.DefaultWorkingDirectory)\Elizium.FakeBuddy\Output\Elizium.FakeBuddy) does not work.

Setting additionalModulePath to the psd1 in that directory does not work.

The documentation says this:

> Path to additional PowerShell modules - Any additional module paths that should be prepended to the PSModulePath before running Pester.

but this doesnt specify what input this refers to. If I assume it is the *additionalModulePath* input, then setting it to "$(System.DefaultWorkingDirectory)\Elizium.FakeBuddy\Output\Elizium.FakeBuddy" (ie the module just built), should work but it doesnt.

Actually, to come to think of it, it may have something to do with using invoke-build. I use invoke-build locally and that works. In fact invoke-build is used in the previous task PowerShell@2 to build the module. Should Pester just run an invoke-build task? What do I have to do here??

Here is the log showing the failure:

```
Starting discovery in 3 files.

Discovery finished in 202ms.

[-] Describe join-AllSchemas failed

 FileNotFoundException: The specified module '.\Output\Elizium.FakeBuddy\Elizium.FakeBuddy.psm1' was not loaded because no valid module file was found in any module directory.
 at <ScriptBlock>, /home/vsts/work/1/s/Elizium.FakeBuddy/Tests/Internal/join-AllSchemas.tests.ps1:4

[-] Describe merge-SettingsContent failed

 FileNotFoundException: The specified module '.\Output\Elizium.FakeBuddy\Elizium.FakeBuddy.psm1' was not loaded because no valid module file was found in any module directory.
 at <ScriptBlock>, /home/vsts/work/1/s/Elizium.FakeBuddy/Tests/Internal/merge-SettingsContent.tests.ps1:4

[-] Describe ConvertFrom-ItermColors failed


 FileNotFoundException: The specified module '.\Output\Elizium.FakeBuddy\Elizium.FakeBuddy.psm1' was not loaded because no valid module file was found in any module directory.
 at <ScriptBlock>, /home/vsts/work/1/s/Elizium.FakeBuddy/Tests/Public/ConvertFro
m-ItermColors.tests.ps1:4


Tests completed in 641ms

Tests Passed: 0, 
Failed: 12, 
Skipped: 0 
NotRun: 0

BeforeAll \ AfterAll failed: 3

  - join-AllSchemas
  - merge-SettingsContent
  - ConvertFrom-ItermColors

##[error]Write-Error: Pester Failed at least one test. Please see results for details.

##[debug]Processed: ##vso[task.issue type=error;]Write-Error: Pester Failed at least one test. Please see results for details.%0A
##[debug]task result: Failed
##[error]Write-Error: Pester Failed at least one test. Please see results for details.

##[debug]Processed: ##vso[task.issue type=error;]Write-Error: Pester Failed at least one test. Please see results for details.%0A
##[debug]Processed: ##vso[task.complete result=Failed;]Write-Error: Pester Failed at least one test. Please see results for details.%0A
Pester Script finished
Finishing: Pester
```
... so you can see that Pester can find the tests, but is not running them correctly for whatever reason.

I changed additionalModulePath to $(System.DefaultWorkingDirectory)\Elizium.FakeBuddy\Output

 Seeing this in the log

> Adding additional module path [/home/vsts/work/1/s\Elizium.FakeBuddy\Output] to $env:PSModulePath

makes me think this is correct. Perhaps Pester is not importing the generated module. How can I enforce this additional import?

But the question is, if I build a module in 1 task, is that module available in the following task. WHat happens in between tasks, are directories deleted? Do I have to combine them both into the same task, if so how? Pester can't build a module, and the PowerShell@2 task can't run the test, otherwise there would be no need for this (AzureDevOpsExtension) module right??

**Comment by plastikfan** [comment]
I also tried to force import the module using the scriptblock input:

> ScriptBlock: '{ import-module Elizium.FakeBuddy -force} '

```yaml
      - task: Pester@10
        inputs:
          PesterVersion: 'LatestVersion|OtherVersion'
          preferredPesterVersion: '5.0.3'
          scriptFolder: '$(System.DefaultWorkingDirectory)\Elizium.FakeBuddy\Tests\*'
          resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
          usePSCore: true
          ScriptBlock: '{ import-module Elizium.FakeBuddy -force} '
          additionalModulePath: '$(System.DefaultWorkingDirectory)\Elizium.FakeBuddy\Output'
```

but this makes no difference.
