### ISSUE TITLE
NUnit2.5 is not a valid Pester export format

### ISSUE THREAD

**Issue by The-New-Guy** [pester/AzureDevOpsExtension#52]
### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS) - On-Premises Build Agent

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*
10.2.4

### Expected behaviour and actual behaviour
Expected: TestResult Object and Code Coverage output files are created.
Actual: Neither file mentioned above are created. When attempting to write out the TestResult object there is an error as seen below:

```
System.Management.Automation.RuntimeException: 'NUnit2.5' is not a valid Pester export format.
at Export-PesterResults, C:\Users\totallyRealUser\Documents\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 14335
at Invoke-Pester<End>, C:\Users\totallyRealUser\Documents\WindowsPowerShell\Modules\Pester\5.1.0\Pester.psm1: line 4871
at <ScriptBlock>, C:\BuildAgent\AzureDevOps\_work\_tasks\Pester_cca5462b-887d-4617-bf3f-dcf0d3c622e9\10.2.4\Pester.ps1: line 142
at <ScriptBlock>, <No file>: line 1
```

### Steps to reproduce the problem

```yaml
- task: Pester@10
    displayName: Pester Test Runner
    inputs:
      TestFolder: $(Build.ArtifactStagingDirectory)
      resultsFile: $(Build.ArtifactStagingDirectory)\Test-Results\Test-Pester.XML
      CodeCoverageOutputFile: $(Build.ArtifactStagingDirectory)\Test-Results\CodeCoverage-Pester.XML
      CodeCoverageFolder: $(Build.ArtifactStagingDirectory)
```

### Additional Info

This issue recently opened for Pester seems related: https://github.com/pester/Pester/issues/1794 .

If I'm reading that issue correctly, the TestResult.OutputFormat has been ignored up until Pester 5.1, and it just always used NUnit2.5. In this version of Pester `NUnit2.5` is not a valid option. However, `NUnitXml` appears to be the current replacement. It looks like the lines below could be changed to fix this.

https://github.com/pester/AzureDevOpsExtension/blob/73572ac06e800032bb2bb171c27d65c020b98b3e/Extension/PesterTask/PesterV10/Pester.ps1#L95-L99
